name: Staging deployment of taxi driver app
on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploying changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ADMINHOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd taxi-reference-bpp/
          git checkout main
          git pull
          npm install
          npm run build
          pm2 kill
          sleep 10
          pm2 serve build 3000 --spa
